server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    types {
        application/javascript js mjs;
        text/css css;
        text/html html;
    }
}
