apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/nadav111/chatable/frontend:latest
        imagePullPolicy:
           - name: ghcr-secret
        ports:
        - containerPort: 80