spec:
  template:
    spec:
      containers:
        - name: backend
          image: ghcr.io/nadav111/chatable/backend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
          env:
            - name: DATABASE_HOST
              value: "db-service"
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DATABASE_HOST):5432/$(POSTGRES_DB)"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
      imagePullSecrets:
        - name: ghcr-secret