name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images
        run: |
          docker build -t backend:latest ./backend
          docker build -t frontend:latest ./frontend

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push images
        run: |
          docker tag backend:latest ghcr.io/nadav111/chatable/backend:latest
          docker tag frontend:latest ghcr.io/nadav111/chatable/frontend:latest
          docker push ghcr.io/nadav111/chatable/backend:latest
          docker push ghcr.io/nadav111/chatable/frontend:latest

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CLUSTER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /opt/app
            docker-compose pull       # pull the latest images
            docker-compose down       # stop old containers
            docker-compose up -d      # start new containers